/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NavBar: typeof import('./src/components/general/NavBar/NavBar.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
    SvgIcon: typeof import('./src/components/general/SvgIcon/SvgIcon.vue')['default']
  }
}
